// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuORmo6RF7UYzXZ2HqqN7caoy-npNpn5M',
    appId: '1:232838126652:web:231ca84313ed82e82eb739',
    messagingSenderId: '232838126652',
    projectId: 'enseignezmoi-26722',
    authDomain: 'enseignezmoi-26722.firebaseapp.com',
    storageBucket: 'enseignezmoi-26722.appspot.com',
    measurementId: 'G-TWF37BS6RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Atu__nteVR4CFWGLqGkLo7pWDSxA6tg',
    appId: '1:232838126652:android:8fb4dc0c8b6112772eb739',
    messagingSenderId: '232838126652',
    projectId: 'enseignezmoi-26722',
    storageBucket: 'enseignezmoi-26722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRWkvb14c9e6DC29o0l4Ek5E4_EqQwxE4',
    appId: '1:232838126652:ios:84e175c0d4e192a82eb739',
    messagingSenderId: '232838126652',
    projectId: 'enseignezmoi-26722',
    storageBucket: 'enseignezmoi-26722.appspot.com',
    iosBundleId: 'com.royaldev.monMaitreDeMaison',
  );
}
